### ISSUE TITLE
Example of how to configuration the Key=Value for ai

### ISSUE THREAD

**Issue by Incarnation-p-lee** [paketo-buildpacks/azure-application-insights#69]
## What happened?
I have below image.yml which can capture the layer of agent but keep rasing **Please provide connection string or instrumentation key.** when docker run.
As I understanding, it should match the `Binding` structure as below but looks little mismatch for this structure. Is there any example for this scenarios ? Thanks a lot.

```go
// Binding is a projection of metadata about an external entity to be bound to.
type Binding struct {
	// Name is the name of the binding
	Name string

	// Path is the path to the binding directory.
	Path string

	// Type is the type of the binding.
	Type string

	// Provider is the optional provider of the binding.
	Provider string

	// Secret is the secret of the binding.
	Secret map[string]string
}
```

https://github.com/buildpacks/libcnb/blob/c07e39f24859ebb30db0d26ed2c555899135dfc0/platform.go#L52-L69

```yaml
...
  build:
    bindings:
    - name: appinsights
      type: ApplicationInsights
      secretRef:
        name: secret
      metadataRef:
        name: configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: build-service
data:
  kind: maven
  provider: test-meta
  type: ApplicationInsights
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: build-service
stringData:
  CONNECTION_STRING: "xxxxx"
```

Error logs
```
Setting Active Processor Count to 8
Calculating JVM memory based on 24543008K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx24145852K -XX:MaxMetaspaceSize=89955K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 24543008K, Thread Count: 50, Loaded Class Count: 13468, Headroom: 0%)
Adding 129 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_azul-zulu/java-security-properties/java-security.properties -agentpath:/layers/paketo-buildpacks_azul-zulu/jvmkill/jvmkill-1.16.0-RELEASE.so=printHeapHistogram=1 -javaagent:/layers/paketo-buildpacks_azure-application-insights/azure-application-insights-java/applicationinsights-agent-3.1.0.jar -XX:ActiveProcessorCount=8 -XX:MaxDirectMemorySize=10M -Xmx24145852K -XX:MaxMetaspaceSize=89955K -XX:ReservedCodeCacheSize=240M -Xss1M -Dorg.springframework.cloud.bindings.boot.enable=true
2021-06-28 10:30:11.080Z ERROR c.m.applicationinsights.agent -
*************************
ApplicationInsights Java Agent 3.1.0 failed to start
*************************
Description:
No connection string or instrumentation key provided

Action:
Please provide connection string or instrumentation key.
```

* What were you attempting to do?

* What did you expect to happen?

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
You might want to give this demo a try: 

https://github.com/paketo-buildpacks/samples/tree/main/java/application-insights

It has instructions and a sample binding. Confirm that works with Docker, then try on K8s. It should work exactly the same, you just have a different process for adding the binding.

**Comment by dmikusa-pivotal** [comment]
Not tested, but I think you want this:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: build-service
stringData:
  InstrumentationKey: "xxxxx"
```

The `stringData` key name, i.e. `InstrumentationKey`, is going to be turned into a file. The name needs to match what is expected, see https://github.com/paketo-buildpacks/samples/blob/main/java/application-insights/binding/InstrumentationKey from the example as that file name is expected.

Hope that helps!

**Comment by dmikusa-pivotal** [comment]
Well, the buildpack will only work with a binding. That said, the binding is just being transferred into an env variable that the AI Java agent is picking up.

See https://github.com/paketo-buildpacks/azure-application-insights/blob/main/helper/properties.go#L49

It basically takes the value from `InstrumentationKey` and populates the env variable `APPLICATIONINSIGHTS_INSTRUMENTATIONKEY`  with that value.

So you could manually configure that. You'd need to manually configure the Agent too though, as the agent is only installed if the binding is present at build time. So you'd end up basically doing everything the buildpack does manually.

**Comment by Incarnation-p-lee** [comment]
Thanks a lot. I also notice that part. Does it mean the AI agent will consume the env `APPLICATIONINSIGHTS_INSTRUMENTATIONKEY`, right ?
If it only transfer the `secret` to env by adding `APPLICATIONINSIGHTS_` prefix, it should also work well with the `connect_string` from `secret`, which also accepted by AI agent also.

**Comment by dmikusa-pivotal** [comment]
Possibly. The code is going to look for a binding with the type of `ApplicationInsights`. It should find your binding if you have the type set to that, which you do. So it seems like it should see your key of `CONNECTION_STRING` and turn that into `APPLICATIONINSIGHTS_CONNECTION_STRING` and populate that env variable with the value you set.

You should be able to confirm that by looking at the environment variables set for your app. When you build your image, run  `docker run --rm --entrypoint launcher -it <your-app-image> bash` to get a shell, followed by `env` or `echo` to print your env variables. The key is to invoke the launcher so it populates all the env variables correctly. That will also only work for images built from the base or full builder. The tiny builder doesn't include a shell, but that would only be used for Java native image apps, at the moment.

Also, keep in mind that we're packaging a specific version of the AI agent, so make sure that version supports the env variable you intend to use https://github.com/paketo-buildpacks/azure-application-insights/blob/main/buildpack.toml#L35-L45.

Hope that helps!

**Comment by Incarnation-p-lee** [comment]
Sure, let me double check and back to you later.

**Comment by Incarnation-p-lee** [comment]
@dmikusa-pivotal 
Sorry for late response due to even higher task interrupt. I have a try with below command but I cannot see any env we expected.
```
docker run --rm --entrypoint launcher -ti xxxxx.azurecr.io/test-0:panli-0701-0 bash
cnb@51c76fb3ff1f:/workspace$ env | grep APPLICATION
BPI_APPLICATION_PATH=/workspace
cnb@51c76fb3ff1f:/workspace$
```

We use `Paketo Azure Application Insights Buildpack 4.4.2`, and our image.yml may looks like below.
```yaml
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: test
  namespace: build-service
spec:
  tag: xxxxxxx.azurecr.io/test-0:panli-0701-0
  serviceAccount: sa-build-service
  builder:
    name: standard-builder
    kind: Builder
  source:
    git:
      url: https://github.com/Incarnation-p-lee/asc-app
      revision: master
  build:
    bindings:
    - name: appinsights
      type: ApplicationInsights
      metadataRef:
        name: configmap
      secretRef:
        name: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: build-service
type: Opaque
stringData:
  instrumentationkey: "xxxxx"
  connection-string: "xxxx"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: build-service
data:
  kind: maven
  provider: test-meta
  type: ApplicationInsights
```

We can also notice the `detect` and `build` phase the binding is mounted as expected.
```
      /platform/bindings/appinsights/metadata from binding-metadata-appinsights (ro)
      /platform/bindings/appinsights/secret from binding-secret-appinsights (ro)
```

**Comment by dmikusa-pivotal** [comment]
Sorry, I overlooked this previously. Please try `docker run --rm --entrypoint launcher -ti xxxxx.azurecr.io/test-0:panli-0701-0 bash` and also add in a `-v` argument to map in the volume for your binding. The volume binding must be present at runtime as well. The env variables are set at runtime based on the binding, they are not embedded in the image, so the binding has to be present at runtime. 

The other option you could do to spy on the env variables would be to `ssh` into a running container, find the pid for your process and then `cat /proc/<pid>/environ`. That'll give you the actual environment used to execute the pid.

**Comment by Incarnation-p-lee** [comment]
Cool, let me have a try.

**Comment by Incarnation-p-lee** [comment]
@dmikusa-pivotal 
I am a little confused about how it works, does it mean the secret as below need to be mounted as volumn to `/platform/bindings/appinsights`, right ?

For example, below secret need to be mounted to `/platform/bindings/appinsights` with key under it. I am not sure if I understand it correctly. 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: build-service
type: Opaque
stringData:
  instrumentationkey: "xxxxx"
  connection-string: "xxxx
```
